"""
projeceuler.net - problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

limit = 4000000
curr = 2
prev = 1
n = 0
evenSum = 2;

while n < limit:
	n = curr + prev
	#print n
	prev = curr
	curr = n
	if n % 2 == 0:
		evenSum+=n
	
print evenSum